#!/bin/bash

## Copyright (C) 2020 - 2020 ENCRYPTED SUPPORT LP <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

for url in $(/usr/share/sdwdate/onion_list_all) ; do
   url_https="$(echo "$url" | str_replace "http://" "https://")"
   curl --head "$url_https"
done
