#! /usr/bin/env python

## TODO:
## - add dependency python-requests to debian/control
## - add dependency python-dateutil to debian/control
## - any reason good reason to use libcurl instead or does python-requests support all we need?
## - check if it really uses "--head" by inspecting traffic
## - command line parameter to maybe use https (as option true or false [not for .onion])
## - command line parameter to set url
## - command line parameter for proxy settings yes/no
## - command line parameter verbose option?
## - command line parameter for curl user agent
## - command line parameter for timeout
## - error handling
## - anything else?

import requests
import sys
from dateutil.parser import parse

url = "https://check.torproject.org"

## Does not support socks proxies yet.
## https://github.com/kennethreitz/requests/issues/2156
proxies = {
    'http' : "socks5://127.0.0.1:9050",
    'https' : "socks5://127.0.0.1:9050"
}

proxies = {
  "http": "http://127.0.0.1:9050",
  "https": "http://127.0.0.1:9050",
}

try:
   response = requests.head(url, proxies=proxies)
except requests.exceptions.ConnectionError as e:
   print >> sys.stderr, "Request failed. | url: %s | ConnectionError: %s" % (url, e)
   sys.exit(1)

content = response.headers
date = response.headers.get('date')

try:
   ## Thanks to:
   ## eumiro
   ## http://stackoverflow.com/a/3894047/2605155
   unixtime = parse(date).strftime('%s')
except ValueError as e:
   print >> sys.stderr, "Parsing date from server failed. | date: %s | dateutil ValueError: %s" % (date, e)
   sys.exit(2)

print "%s" % (unixtime)

sys.exit(0)
