#! /usr/bin/env python

## TODO:
## - add dependency python-requests to debian/control
## - add dependency python-dateutil to debian/control
## - any reason good reason to use libcurl instead or does python-requests support all we need?
## - timeout
## - check if it really uses "--head" by inspecting traffic
## - command line parameter to maybe use https (as option true or false [not for .onion])
## - command line parameter to set url
## - command line parameter for proxy settings yes/no
## - command line parameter verbose option?
## - command line parameter for curl user agent
## - anything else?

import requests
import sys
from dateutil.parser import parse

url = "http://www.cnn.com"

import requests
response = requests.head(url)
content = response.headers
date=response.headers.get('date')

## Thanks to:
## eumiro
## http://stackoverflow.com/a/3894047/2605155
unixtime=parse(date).strftime('%s')
print "%s" % (unixtime)
sys.exit(0)
