#!/bin/bash

## Copyright (C) 2012 - 2021 ENCRYPTED SUPPORT LP <adrelanos@whonix.org>
## See the file COPYING for copying conditions.

#### meta start
#### project Whonix and Kicksecure
#### category time and Tor
#### description
## start `anondate-set` when `sdwdate` creates file
## `/run/sdwdate/request_anondate-set`.
##
## This script allows `sdwdate` to request restart of Tor through creation of
## file `/run/sdwdate/request_anondate-set`.
##
## This is an alternative to avoid having to weaken `sdwdate` hardening (`systemd`,
## `apparmor`) while permitting `sdwdate` to restart of Tor.
##
## The script `sdwdate` executes the -> `/usr/libexec/helper-scripts/onion-time-pre-script` script,
## which creates file `/run/sdwdate/request_anondate-set` -> which results in this script running
## `anondate-set` -> which results in:
## - If a Tor restart is required and if already running, restart Tor.
## - Delete Tor consensus using the `anon-consensus-del` script.
## - Restart Tor if it was previously running.
#### meta end

set -x
set -e

## inotifywait requires the folder to already exist.
mkdir --parents /run/sdwdate
chown --recursive sdwdate:sdwdate /run/sdwdate

inotifywait_subshell_fifo="$(mktemp)"
rm --force "$inotifywait_subshell_fifo"
mkfifo "$inotifywait_subshell_fifo"

{
   inotifywait --quiet --recursive --monitor --event create --format "%w%f" "/run/sdwdate/" &
   wait "$!"

} > "$inotifywait_subshell_fifo" &

inotifywait_subshell_pid="$!"

if [ -f "/run/sdwdate/request_anondate-set" ]; then
   anondate-set || true
   rm -f /run/sdwdate/request_anondate-set
fi

while read file_name; do
   if [ "$file_name" = "/run/sdwdate/request_anondate-set" ] ; then
      anondate-set || true
      rm -f /run/sdwdate/request_anondate-set
   fi
done < "$inotifywait_subshell_fifo"

wait "$inotifywait_subshell_pid"
