#!/bin/bash

## Copyright (C) 2017 - 2021 ENCRYPTED SUPPORT LP <adrelanos@whonix.org>
## See the file COPYING for copying conditions.

set -x
set -e

date_cmd(){
   date -u +"%Y-%m-%d %T"
}

output_cmd() {
   msg="$(date_cmd) - $0 - $@"
   echo "$msg"
   echo "$msg" | systemd-cat --identifier="suspend-pre" || true
}

if [ -f /run/qubes/this-is-templatevm ]; then
   output_cmd "INFO - Skipping, because run in TemplateVM."
   exit 0
fi

if [ ! "$(id -u)" = "0" ]; then
   output_cmd "ERROR - Must run as root!"
   exit 2
fi

if command -v "qubesdb-read" >/dev/null 2>&1 ; then
   true
else
   output_cmd "INFO - Clock fix after resume not implemented in Non-Qubes-Whonix. See: https://www.whonix.org/wiki/Troubleshooting#Clock_Fix"
   exit 3
fi

## Defensive measure to not mess up file permissions.
mkdir --parents /run/sdwdate
chown --recursive sdwdate:sdwdate /run/sdwdate

## First stop sdwdate, then stop Tor.
## Should sdwdate fetch time during run of this script, it would log
## unnecessary fetching errors.

if systemctl --no-pager status sdwdate >/dev/null ; then
   output_cmd "INFO - Creating /run/sdwdate/sdwdate_was_running.status..."
   touch /run/sdwdate/sdwdate_was_running.status
   output_cmd "INFO - Done, created /run/sdwdate/sdwdate_was_running.status."

   output_cmd "INFO - Stopping sdwdate..."
   systemctl --no-pager stop sdwdate
   output_cmd "INFO - Done, stopped sdwdate."

   output_cmd "INFO - Deleting /run/sdwdate/first_success..."
   rm --force /run/sdwdate/first_success
   output_cmd "INFO - Done, deleted /run/sdwdate/first_success."

   output_cmd "INFO - Deleting /run/sdwdate/success..."
   rm --force /run/sdwdate/success
   output_cmd "INFO - Done, deleted /run/sdwdate/success."

   if command -v whonix_firewall >/dev/null 2>&1 ; then
      ## Whonix firewall timesync-fail-closed mode
      output_cmd "INFO - Entering Whonix firewall timesync-fail-closed mode."
      firewall_mode="timesync-fail-closed" whonix_firewall
      output_cmd "INFO - Done, entered Whonix firewall timesync-fail-closed mode."
   else
      true "$0 INFO: Whonix firewall not installed, probably running outside of Whonix."
   fi
else
   output_cmd "INFO - sdwdate was not running, no need to stop it."
fi

if systemctl --no-pager status tor@default >/dev/null ; then
   output_cmd "INFO - Creating /run/sdwdate/tor_was_running.status..."
   touch /run/sdwdate/tor_was_running.status
   output_cmd "INFO - Done, created /run/sdwdate/tor_was_running.status."

   output_cmd "INFO - Stopping Tor..."
   systemctl --no-pager stop tor@default
   output_cmd "INFO - Done, stopped Tor."
else
   output_cmd "INFO - Tor was not running, no need to stop it."
fi
