#!/bin/bash

## Copyright (C) 2017 - 2021 ENCRYPTED SUPPORT LP <adrelanos@whonix.org>
## See the file COPYING for copying conditions.

set -x
set -e

date_cmd(){
   date -u +"%Y-%m-%d %T"
}

output_cmd() {
   msg="$(date_cmd) - $0 - $@"
   echo "$msg"
   echo "$msg" | systemd-cat --identifier="suspend-pre" || true
}

if [ -f /run/qubes/this-is-templatevm ]; then
   output_cmd "INFO - Skipping, because run in TemplateVM."
   exit 0
fi

if [ ! "$(id -u)" = "0" ]; then
   output_cmd "ERROR - Must run as root!"
   exit 2
fi

if command -v "qubesdb-read" >/dev/null 2>&1 ; then
   true
else
   output_cmd "INFO - Clock fix after resume not implemented in Non-Qubes-Whonix. See: https://www.whonix.org/wiki/Troubleshooting#Clock_Fix"
   exit 3
fi

## Defensive measure to not mess up file permissions.
mkdir --parents /run/sdwdate
chown --recursive sdwdate:sdwdate /run/sdwdate

tor_restart_maybe() {
   if test -f /run/sdwdate/tor_was_running.status ; then
      output_cmd "INFO - Deleting /run/sdwdate/tor_was_running.status..."
      rm --force /run/sdwdate/sdwdate_was_running.status
      output_cmd "INFO - Done, deleted /run/sdwdate/tor_was_running.status."

      output_cmd "INFO - Restarting Tor..."
      systemctl --no-pager restart tor@default
      output_cmd "INFO - Done, restarted Tor."
   else
      output_cmd "INFO - File /run/sdwdate/tor_was_running.status did not exist, meaning we previously did not stop Tor so not starting it now."
   fi
}

## Previously in suspend-pre sdwdate
## - Tor was stopped.
## - sdwdate was stopped.
## - Whonix firewall entered timesync-fail-closed mode.
##
## Now in this script:
## - 1. roughly fix the time using `date`
## - 2. restart Tor
## - 3. sdwdate-clock-jump so it also sets the time using `date`
## - 4. (outside of this script) Once sdwdate succeeded,
##      whonix-firewall-sdwdate-watcher.service should enter Whonix firewall in
##      full mode.
##
## For an ISP level observer this should look like a reboot.

## Do not interfere with the clock if the service was stopped.
if test -f /run/sdwdate/sdwdate_was_running.status ; then
   output_cmd "INFO - Deleting /run/sdwdate/sdwdate_was_running.status..."
   rm --force /run/sdwdate/sdwdate_was_running.status
   output_cmd "INFO - Done, deleted /run/sdwdate/sdwdate_was_running.status."

   ## Workaround for a Qubes bug.
   ## https://github.com/Whonix/updates-status/issues/1
   randomized_unix_time="$(timeout --kill-after="5" "5" /usr/lib/qubes/qrexec-client-vm dom0 qubes.GetRandomizedTime)" || \
      output_cmd "ERROR - /usr/lib/qubes/qrexec-client-vm had non-zero exit code."

   if [[ "$randomized_unix_time" =~ ^[+-]?[0-9]+\.?[0-9]*$ ]]; then
      output_cmd "INFO - date before roughly fixing it: $(date --utc)"
      date --utc --set "@$randomized_unix_time" >/dev/null
      output_cmd "INFO - date after roughly fixing it : $(date --utc)"
   else
      output_cmd "ERROR - randomized_unix_time: '$randomized_unix_time'"
   fi

   tor_restart_maybe

   output_cmd "INFO - Running sdwdate-clock-jump..."
   sdwdate-clock-jump
   output_cmd "INFO - Done, with sdwdate-clock-jump."

   ## Whonix firewall full mode
   ##
   ## After sdwdate restart, sdwdate will on success recreate the status file
   ## '/run/sdwdate/first_success'.
   ##
   ## ( whonix-[gw|ws]-firewall ) /lib/systemd/system/whonix-firewall-sdwdate-watcher.service /
   ## ( helper-scripts ) /usr/libexec/helper-scripts/firewall-restarter
   ## will notice this, and restart Whonix firewall in full mode.

   exit 0
else
   output_cmd "INFO - File /run/sdwdate/sdwdate_was_running.status did not exist, meaning we previously did not stop sdwdate so not starting it now."
fi

## Make sure Tor is restarted even if sdwdate was not running during suspend-pre.
tor_restart_maybe
