#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

## CREDITS
## - sdwdate is a rewrite of tails_htp in bash
## - defaults taken from tails_htp
## - options inspired by tails_htp
## - log file layout inspired by tails_htp
## - sclockadj has been written by Jason Ayala (Jason@JasonAyala.com)

## TODO:
## - implement --user

sdwdate_usage() {
   echo "\
$SCRIPTNAME [-aDdlpqTux] [long options...]
        -d --debug                            debug
        --help                                print usage message and exit
        -q --quiet                            quiet
        -x --dont_set_date                    do not set the time (only show)
        --no-move-forward                     do not move the time forward
        --no-move-backwards                   do not move the time backwards
        --systohc                             update hardware clock
        -a --user_agent                       http user agent to use
        -l --log_file                         log to this file rather than to STDOUT
        -D --done_file                        create this file after one cycle of sdwdate
        -T --success_file                     create this file after setting time successfully
        --first_success_file                  create this file after setting time successfully for the first time
        --pool_one                            distrusted hostnames
        --pool_two                            distrusted hostnames
        --pool_three                          distrusted hostnames
        --allowed_per_pool_failure_ratio      ratio (0.0-1.0) of allowed per-pool failure
        -p --proxy-ip                         proxy IP
        -o --port-port                        proxy port
        -i --interval                         continuously run every x minutes
        --mininterval                         wait minimum between intervals
        -r --randomize                        randomize interval
        -n --noconfig                         ignore /etc/sdwdate.d/ config folder
        --parsecmd_only_on_startup            parse command line arguments only on startup
        -w --dispatchpre                      exec before run
        -y --dispatchprerequisite             check before run
        -x --dispatchpostsuccess              exec after successful run
        -z --dispatchpostfailure              exec after unsuccessful run
        -m --dispatchposterror                exec when an error is caught
        --dispatch_pre_one                    exec before run of url to unixtime tool
        --dispatch_post_one                   exec after run of url to unixtime tool
        --dispatch_pre_two                    exec before run of url to unixtime tool
        --dispatch_post_two                   exec after run of url to unixtime tool
        --dispatch_pre_three                  exec before first run of url to unixtime tool
        --dispatch_post_three                 exec after run of url to unixtime tool
        --nodonefileonerror                   do not create done file on error
        --noexitonerror                       do not exit on error
        --echo-unixtime                       echo remote unix time even when using --quiet"

#       -u --user                             userid to run as
}

sdwdate_defaults() {
   if [ "$DEBUG" = "" ]; then
      DEBUG="0"
   fi

   if [ "$USER" = "" ]; then
      USER=""
   fi

   if [ "$DONT_SET_DATE" = "" ]; then
      DONT_SET_DATE="0"
   fi

   if [ "$NO_MOVE_FORWARD" = "" ]; then
      NO_MOVE_FORWARD=1
   fi

   if [ "$NO_MOVE_BACKWARDS" = "" ]; then
      NO_MOVE_BACKWARDS=1
   fi

   if [ "$SYSTOHC" = "" ]; then
      SYSTOHC=0
      SDWDATE_SCLOCKADJ_SYSTOHC="--nosystohc"
   fi

   if [ "$LOG_FILE" = "" ]; then
      LOG_FILE=~/.sdwdate/log
   fi

   if [ "$DONE_FILE" = "" ]; then
      DONE_FILE=~/.sdwdate/done
   fi

   if [ "$SUCCESS_FILE" = "" ]; then
      SUCCESS_FILE=~/.sdwdate/success
   fi

   if [ "$FIRST_SUCCESS_FILE" = "" ]; then
      FIRST_SUCCESS_FILE=~/.sdwdate/first_success
   fi

   if [ "$ALLOWED_PER_POOL_FAILURE_RATIO" = "" ]; then
      ALLOWED_PER_POOL_FAILURE_RATIO="0.34"
   fi

   if [ "$TEMP_DIR" = "" ]; then
      TEMP_DIR="$(mktemp --directory)"
   fi
   ## Export so plugins run by sdwdate can use it.
   export TEMP_DIR

   if [ "$SDW_CACHE_DIR" = "" ]; then
      SDW_CACHE_DIR="/var/cache/sdwdate/sclockadj"
   fi

   if [ "$PROXY_IP" = "" ]; then
      PROXY_IP="127.0.0.1"
   fi

   if [ "$PROXY_PORT" = "" ]; then
      PROXY_PORT="9050"
   fi

   if [ "$INTERVAL" = "" ]; then
      INTERVAL=""
   fi

   if [ "$MIN_INTERVAL" = "" ]; then
      MIN_INTERVAL="10"
   fi

   if [ "$NOCONFIG" = "" ]; then
      NOCONFIG=""
   fi

   if [ "$PARSE_CMD_ONLY_ON_STARTUP" = "" ]; then
      PARSE_CMD_ONLY_ON_STARTUP=""
   fi

   if [ "$RANDOMIZE" = "" ]; then
      RANDOMIZE=""
   fi

   if [ "$DISPATCH_PREREQUISITE" = "" ]; then
      DISPATCH_PREREQUISITE="true"
   fi

   if [ "$DISPATCH_POST_ERROR" = "" ]; then
      DISPATCH_POST_ERROR="exit 1"
   fi

   if [ "$SDW_TOUCH_DONE_FILE_ON_ERROR" = "" ]; then
      SDW_TOUCH_DONE_FILE_ON_ERROR="1"
   fi

   if [ "$SDW_EXIT_ON_ERROR" = "" ]; then
      SDW_EXIT_ON_ERROR="1"
   fi

   if [ "$DISPATCH_PRE" = "" ]; then
      DISPATCH_PRE="true"
   fi

   if [ "$DISPATCH_POST_SUCCESS" = "" ]; then
      DISPATCH_POST_SUCCESS="true"
   fi

   if [ "$DISPATCH_POST_FAILURE" = "" ]; then
      DISPATCH_POST_FAILURE="true"
   fi

   if [ "$HTTP_USER_AGENT" = "" ]; then
      HTTP_USER_AGENT=""
      #HTTP_USER_AGENT="$(/usr/bin/getTorbuttonUserAgent)"
      #HTTP_USER_AGENT="Mozilla/5.0 (Windows NT 6.1; rv:10.0) Gecko/20100101 Firefox/10.0"
   fi

   if [ "$SDWDATE_USE_SCLOCKADJ_WHEN_STARTUP" = "" ]; then
      SDWDATE_USE_SCLOCKADJ_WHEN_STARTUP="0"
   fi

   if [ "$SDWDATE_USE_SCLOCKADJ_WHEN_RESTARTUP" = "" ]; then
      SDWDATE_USE_SCLOCKADJ_WHEN_RESTARTUP="1"
   fi

   if [ "$SDWDATE_USE_SCLOCKADJ_WHEN_DAEMON" = "" ]; then
      SDWDATE_USE_SCLOCKADJ_WHEN_DAEMON="1"
   fi

   if [ "$SDWDATE_SCLOCKADJ_VERBOSE" = "" ]; then
      SDWDATE_SCLOCKADJ_VERBOSE="--no-verbose"
   fi

   if [ "$SDWDATE_SCLOCKADJ_CHANGE_DATE" = "" ]; then
      SDWDATE_SCLOCKADJ_CHANGE_DATE="--no-debug"
   fi

   if [ "$SDWDATE_SCLOCKADJ_FIRST_WAIT" = "" ]; then
      SDWDATE_SCLOCKADJ_FIRST_WAIT="--no-first-wait"
   fi

   if [ "$SDWDATE_SCLOCKADJ_MOVE_MIN" = "" ]; then
      SDWDATE_SCLOCKADJ_MOVE_MIN="500000"
   fi

   if [ "$SDWDATE_SCLOCKADJ_MOVE_MAX" = "" ]; then
      SDWDATE_SCLOCKADJ_MOVE_MAX="500000"
   fi

   if [ "$SDWDATE_SCLOCKADJ_WAIT_MIN" = "" ]; then
      SDWDATE_SCLOCKADJ_WAIT_MIN="1000000000"
   fi

   if [ "$SDWDATE_SCLOCKADJ_WAIT_MAX" = "" ]; then
      SDWDATE_SCLOCKADJ_WAIT_MAX="1000000000"
   fi

   if [ "$ECHO_UNIX_TIME" = "" ]; then
      ECHO_UNIX_TIME="false"
   fi

   if [ "${SDWDATE_TIME_TOOL_DISPATCH_PRE[SDWDATE_POOL_ONE]}" = "" ]; then
      declare -A -g SDWDATE_TIME_TOOL_DISPATCH_PRE
      SDWDATE_TIME_TOOL_DISPATCH_PRE[SDWDATE_POOL_ONE]="true"
   fi

   if [ "${SDWDATE_TIME_TOOL_DISPATCH_POST[SDWDATE_POOL_ONE]}" = "" ]; then
      declare -A -g SDWDATE_TIME_TOOL_DISPATCH_POST
      SDWDATE_TIME_TOOL_DISPATCH_POST[SDWDATE_POOL_ONE]="true"
   fi

   if [ "${SDWDATE_TIME_TOOL_DISPATCH_PRE[SDWDATE_POOL_TWO]}" = "" ]; then
      declare -A -g SDWDATE_TIME_TOOL_DISPATCH_PRE
      SDWDATE_TIME_TOOL_DISPATCH_PRE[SDWDATE_POOL_TWO]="true"
   fi

   if [ "${SDWDATE_TIME_TOOL_DISPATCH_POST[SDWDATE_POOL_TWO]}" = "" ]; then
      declare -A -g SDWDATE_TIME_TOOL_DISPATCH_POST
      SDWDATE_TIME_TOOL_DISPATCH_POST[SDWDATE_POOL_TWO]="true"
   fi

   if [ "${SDWDATE_TIME_TOOL_DISPATCH_PRE[SDWDATE_POOL_THREE]}" = "" ]; then
      declare -A -g SDWDATE_TIME_TOOL_DISPATCH_PRE
      SDWDATE_TIME_TOOL_DISPATCH_PRE[SDWDATE_POOL_THREE]="true"
   fi

   if [ "${SDWDATE_TIME_TOOL_DISPATCH_POST[SDWDATE_POOL_THREE]}" = "" ]; then
      declare -A -g SDWDATE_TIME_TOOL_DISPATCH_POST
      SDWDATE_TIME_TOOL_DISPATCH_POST[SDWDATE_POOL_THREE]="true"
   fi

   if [ "$SDWDATE_POOL_ONE" = "" ]; then
      declare -g SDWDATE_POOL_ONE

      SDWDATE_POOL_ONE=(
         boum.org
         chavez.indymedia.org
         db.debian.org
         debian.org
         epic.org
         mail.riseup.net
         sarava.org
         squat.net
         tachanka.org
         www.1984.is
         www.eff.org
         www.immerda.ch
         www.privacyinternational.org
         www.torproject.org
         freedom.press
      )
   fi

   if [ "$SDWDATE_POOL_TWO" = "" ]; then
      declare -g SDWDATE_POOL_TWO

      SDWDATE_POOL_TWO=(
         grc.com
         www.tarsnap.com
         wikileaks.org
         pressfreedomfoundation.org
         securedrop.theguardian.com
         safesource.forbes.com
         en.wikipedia.org
         cve.mitre.org
         duckduckgo.com
         lkml.org
         www.gnu.org
         fsf.org
         fsfe.org
         defectivebydesign.org
         www.kernel.org
         opentechfund.org
         firstlook.org
      )
   fi

   if [ "$SDWDATE_POOL_THREE" = "" ]; then
      declare -g SDWDATE_POOL_THREE

      SDWDATE_POOL_THREE=(
         www.startpage.com
         www.apache.org
         www.centos.org
         www.piratenpartei.de
         www.torservers.net
         www.accessnow.org
         rsf.org
         www.wauland.de
         www.ccc.de
         netzpolitik.org
         privacyfoundation.ch
         www.noisebridge.net
         en.bitcoin.it
         www.calyxinstitute.org
         gnupg.org
         gpgtools.org
         schneier.com
      )
   fi
}

sdwdate_read_config_folder() {
   declare -A -g SDWDATE_TIME_TOOL_DISPATCH_PRE
   declare -A -g SDWDATE_TIME_TOOL_DISPATCH_POST

   if [ "$NOCONFIG" = "1" ]; then
      return 0
   fi
   for i in /etc/sdwdate.d/*; do
      if [ -f "$i" ]; then
         ## If the last character is a ~, ignore that file, because it was created
         ## by some editor, which creates backup files.
         if [ "${i: -1}" = "~" ]; then
            continue
         fi
         ## Skipping files such as .dpkg-old and .dpkg-dist.
         if ( echo "$i" | grep -q ".dpkg-" ); then
            true "skip $i"
            continue
         fi
         local bash_n_exit_code bash_n_output
         bash_n_exit_code="0"
         bash_n_output="$(bash -n "$i" 2>&1)" || { bash_n_exit_code="$?" ; true; };
         if [ ! "$bash_n_exit_code" = "0" ]; then
            sdwdate_error_handler "Invalid config file: $i
bash_n_exit_code: $bash_n_exit_code
bash_n_output:
$bash_n_output" || true
         fi
         source "$i"
      fi
   done
}

sdwdate_parse_cmd_options() {
   ## Thanks to:
   ## http://mywiki.wooledge.org/BashFAQ/035

   while :
   do
       case $1 in
           -h | --help | -\?)
               sdwdate_usage
               exit 0
               ;;
           -d | --debug)
               DEBUG=1
               shift
               ;;
           -u | --user)
               USER=$2
               RUN_AS="sudo -u $USER"
               shift 2
               ;;
           -x | --dont_set_date)
               DONT_SET_DATE=1
               shift
               ;;
           --no-move-forward)
               NO_MOVE_FORWARD=1
               shift
               ;;
           --no-move-backwards)
               NO_MOVE_BACKWARDS=1
               shift
               ;;
           --systohc)
               SYSTOHC=1
               SDWDATE_SCLOCKADJ_SYSTOHC="--systohc"
               shift
               ;;
           -a | --user_agent)
               HTTP_USER_AGENT=$2
               shift 2
               ;;
           -l | --log_file)
               LOG_FILE=$2
               shift 2
               ;;
           -D | --done_file)
               DONE_FILE=$2
               shift 2
               ;;
           -T | --success_file)
               SUCCESS_FILE=$2
               shift 2
               ;;
           -T | --first_success_file)
               FIRST_SUCCESS_FILE=$2
               shift 2
               ;;
           -P | --pool_one)
               SDWDATE_POOL_ONE=$2
               shift 2
               ;;
           -N | --pool_two)
               SDWDATE_POOL_TWO=$2
               shift 2
               ;;
           -F | --pool_three)
               SDWDATE_POOL_THREE=$2
               shift 2
               ;;
           -A | --allowed_per_pool_failure_ratio)
               ALLOWED_PER_POOL_FAILURE_RATIO=$2
               shift 2
               ;;
           -p | --proxy-ip)
               PROXY_IP=$2
               shift 2
               ;;
           -o | --proxy-port)
               PROXY_PORT=$2
               shift 2
               ;;
           -i | --interval)
               INTERVAL=$2
               shift 2
               ;;
           --mininterval)
               MIN_INTERVAL=$2
               shift 2
               ;;
           -n | --noconfig)
               NOCONFIG="1"
               shift 1
               ;;
           --parsecmd_only_on_startup)
               PARSE_CMD_ONLY_ON_STARTUP="1"
               shift 1
               ;;
           -r | --randomize)
               RANDOMIZE="1"
               shift 1
               ;;
           --timewarp-on-startup)
               SDWDATE_USE_SCLOCKADJ_WHEN_STARTUP="0"
               shift 1
               ;;
           --timewarp-on-restartup)
               SDWDATE_USE_SCLOCKADJ_WHEN_RESTARTUP="0"
               shift 1
               ;;
           --timewarp-on-daemon)
               SDWDATE_USE_SCLOCKADJ_WHEN_DAEMON="0"
               shift 1
               ;;
           --sclockadj-on-startup)
               SDWDATE_USE_SCLOCKADJ_WHEN_STARTUP="1"
               shift 1
               ;;
           --sclockadj-on-daemon)
               SDWDATE_USE_SCLOCKADJ_WHEN_DAEMON="1"
               shift 1
               ;;
           --sclockadj-verbose)
               SDWDATE_SCLOCKADJ_VERBOSE="--verbose"
               shift 1
               ;;
           --sclockadj-no-change-date)
               SDWDATE_SCLOCKADJ_CHANGE_DATE="--debug"
               shift 1
               ;;
           --sclockadj-first-wait)
               SDWDATE_SCLOCKADJ_FIRST_WAIT="--first-wait"
               shift 1
               ;;
           --sclockadj-move-min)
               SDWDATE_SCLOCKADJ_MOVE_MIN=$2
               shift 2
               ;;
           --sclockadj-move-max)
               SDWDATE_SCLOCKADJ_MOVE_MAX=$2
               shift 2
               ;;
           --sclockadj-wait-min)
               SDWDATE_SCLOCKADJ_WAIT_MIN=$2
               shift 2
               ;;
           --sclockadj-wait-max)
               SDWDATE_SCLOCKADJ_WAIT_MAX=$2
               shift 2
               ;;
           -y | --dispatchprerequisite)
               DISPATCH_PREREQUISITE=$2
               shift 2
               ;;
           -m | --dispatchposterror)
               DISPATCH_POST_ERROR=$2
               shift 2
               ;;
           --nodonefileonerror)
               SDW_TOUCH_DONE_FILE_ON_ERROR="0"
               shift 2
               ;;
           --noexitonerror)
               SDW_EXIT_ON_ERROR="0"
               shift 2
               ;;
           -w | --dispatchpre)
               DISPATCH_PRE=$2
               shift 2
               ;;
           -x | --dispatchpostsuccess)
               DISPATCH_POST_SUCCESS=$2
               shift 2
               ;;
           -z | --dispatchpostfailure)
               DISPATCH_POST_FAILURE=$2
               shift 2
               ;;
           --dispatch_pre_one)
               SDWDATE_TIME_TOOL_DISPATCH_PRE[SDWDATE_POOL_ONE]=$2
               shift 2
               ;;
           --dispatch_post_one)
               SDWDATE_TIME_TOOL_DISPATCH_POST[SDWDATE_POOL_ONE]=$2
               shift 2
               ;;
           --dispatch_pre_two)
               SDWDATE_TIME_TOOL_DISPATCH_PRE[SDWDATE_POOL_TWO]=$2
               shift 2
               ;;
           --dispatch_post_two)
               SDWDATE_TIME_TOOL_DISPATCH_POST[SDWDATE_POOL_TWO]=$2
               shift 2
               ;;
           --dispatch_pre_three)
               SDWDATE_TIME_TOOL_DISPATCH_PRE[SDWDATE_POOL_THREE]=$2
               shift 2
               ;;
           --dispatch_post_three)
               SDWDATE_TIME_TOOL_DISPATCH_POST[SDWDATE_POOL_THREE]=$2
               shift 2
               ;;
           -q | --quiet)
               QUIET=1
               shift
               ;;
           --echo-unixtime)
               ECHO_UNIX_TIME=true
               shift
               ;;
           --)
               shift
               break
               ;;
           -*)
               sdwdate_log "$SCRIPTNAME unknown option: $1" >&2
               exit 1
               ;;
           *)
               break
               ;;
       esac
   done

   ## If there are input files (for example) that follow the options, they
   ## will remain in the "$@" positional parameters.
}

sdwdate_preparation() {
   mkdir --parents "$(dirname "$LOG_FILE")"
   mkdir --parents "$(dirname "$DONE_FILE")"
   mkdir --parents "$(dirname "$SUCCESS_FILE")"
   mkdir --parents "$(dirname "$FIRST_SUCCESS_FILE")"

   rm --force "$DONE_FILE"
   rm --force "$SUCCESS_FILE"
   #rm --force "$FIRST_SUCCESS_FILE"

   declare -A -g sdwdate_download_tool_exit_code
   declare -A -g SDWDATE_DOWNLOAD_TOOL_PID
   declare -A -g SDWDATE_DOWNLOAD_TOOK_TIME

   if [ "$who_ami" = "" ]; then
      ## Required for eventual plugins.
      who_ami="$(whoami)"
   fi
   sdwdate_log "$FUNCNAME: who_ami is set to $who_ami."
}

sdwdate_echo() {
   if [ "$QUIET" = "1" ]; then
      true
   else
      echo "$@"
   fi
}

sdwdate_write_log() {
   ## Default, if the error happens before defaults are set and before config
   ## files are read.
   if [ "$LOG_FILE" = "" ]; then
      LOG_FILE="/var/log/sdwdate.log"
   fi

   if [ "$LOG_FILE" = "" ]; then
      true
   else
      echo "$@" >> "$LOG_FILE"
   fi
}

sdwdate_log() {
   if [ "$ID" = "" ] ; then
      ID="No_ID"
   fi

   local msg msg_string_length max_log_string_length
   msg="$ID: $@"
   msg_string_length="${#msg}"
   max_log_string_length="500"

   if [ "$msg_string_length" -gt "$max_log_string_length" ]; then
      ## Shorten excess length $msg to $max_log_string_length chars.
      msg="${msg:0:$max_log_string_length}"
      msg="${msg} ||| Shortened log msg string length!"
   fi

   swddate_last_but_one_msg="$swddate_last_msg"
   swddate_last_msg="$msg"

   sdwdate_echo "$msg"
   sdwdate_write_log "$msg"
}

sdwdate_no_duplicate_log() {
   if [ ! -f "$LOG_FILE" ]; then
      sdwdate_log "$@"
      return 0
   fi

   if [ "$swddate_last_msg" = "$ID: $@" ]; then
      return 0
   fi
   if [ "$swddate_last_but_one_msg" = "$ID: $@" ]; then
      return 0
   fi

   sdwdate_log "$@"
}

sdwdate_error_handler() {
   local exit_code="$?"
   local error_cause error_text
   error_text="$1"
   if [ "$error_text" = "" ]; then
      error_cause="$FUNCNAME signal ERR detected with BASH_COMMAND:
$BASH_COMMAND"
   else
      error_cause="$FUNCNAME called with error_text:
$error_text"
   fi

   ## Default, if the error happens before defaults are set and before config
   ## files are read.
   if [ "$SDW_EXIT_ON_ERROR" = "" ]; then
      SDW_EXIT_ON_ERROR="1"
   fi

   local error_message
   error_message="\
############################################
## Error detected! Please report this bug! #
##
## BASH_SOURCE: $BASH_SOURCE
## SDW_EXIT_ON_ERROR: $SDW_EXIT_ON_ERROR
## SDW_MODE: $SDW_MODE
## SDWDATE_SUBSHELL_SCLOCKADJ_EXIT_CODE: $SDWDATE_SUBSHELL_SCLOCKADJ_EXIT_CODE
##
## exit_code: $exit_code
## error_cause: $error_cause
############################################\
"

   sdwdate_log "error_message: $error_message" || true

   error_message="\
############################################<br></br>
## Error detected! Please report this bug! #<br></br>
##<br></br>
## BASH_SOURCE: $BASH_SOURCE<br></br>
## SDW_EXIT_ON_ERROR: $SDW_EXIT_ON_ERROR<br></br>
## SDW_MODE: $SDW_MODE<br></br>
## SDWDATE_SUBSHELL_SCLOCKADJ_EXIT_CODE: $SDWDATE_SUBSHELL_SCLOCKADJ_EXIT_CODE<br></br>
##<br></br>
## exit_code: $exit_code<br></br>
## error_cause: $error_cause<br></br>
############################################<br></br>\
"

   true "DISPATCH_POST_ERROR: $DISPATCH_POST_ERROR"

   local ret
   if [ "$SDW_TOUCH_DONE_FILE_ON_ERROR" = "1" ]; then
      touch "$DONE_FILE"
      ret="$?"
      if [ ! "$ret" = "0" ]; then
         sdwdate_log "ERROR $BASH_SOURCE: Could not touch DONE_FILE: $DONE_FILE." || true
      fi
   fi

   if [ "$DISPATCH_POST_ERROR" = "" ]; then
      true
   else
      sdwdate_log "dispatching post_error (SDW_MODE: $SDW_MODE) (SDW_EXIT_ON_ERROR: $SDW_EXIT_ON_ERROR): $DISPATCH_POST_ERROR" || true
      sdwdate_eval $DISPATCH_POST_ERROR || true
      sdwdate_log "dispatching post_error done." || true
   fi

   if [ "$SDW_EXIT_ON_ERROR" = "1" ]; then
      sdwdate_log "$SCRIPTNAME (not timesync!): Error detected. Cleaning up..." || true
      ## Check if function sdwdate_terminate_sclockadj is already available and
      ## use it if available.
      command_v_exit_code="0"
      command -v sdwdate_terminate_sclockadj >/dev/null 2>&1 || { command_v_exit_code="$?" ; true; };
      if [ "$command_v_exit_code" = "0" ]; then
         sdwdate_terminate_sclockadj || true
      fi
      SIGNAL_TYPE="ERR"
      if [ "$(command -v "sdwdate_ex_funct")" ]; then
         sdwdate_ex_funct || true
      fi
      sdwdate_log "$SCRIPTNAME (not timesync!): Error detected. Exiting." || true
      exit 1
   else
      sdwdate_log "$SCRIPTNAME (not timesync!): Error detected. Continuing." || true
   fi
}

sdwdate_sanity_tests() {
   if [ "$ID" = "" ]; then
      sdwdate_error_handler "Variable ID is empty." || true
   fi

   command -v bash >/dev/null
   command -v bc >/dev/null
   command -v basename >/dev/null
   command -v mktemp >/dev/null
   command -v touch >/dev/null
   command -v dirname >/dev/null
   command -v awk >/dev/null
   command -v date >/dev/null
   ## Using GNU's printf instead of bash's printf.
   command -v /usr/bin/printf >/dev/null
   command -v od >/dev/null
   command -v grep >/dev/null
   command -v sudo >/dev/null
   command -v shuf >/dev/null
   command -v /usr/lib/sdwdate/sclockadj >/dev/null
   command -v /sbin/hwclock >/dev/null
   command -v /usr/lib/sdwdate/url_to_unixtime >/dev/null
   command -v timeout >/dev/null

   test -e "/dev/random"
   bash -n "$BASH_SOURCE"
}

sdwdate_ex_funct() {
   sdwdate_log "$SCRIPTNAME (not timesync!): signal $SIGNAL_TYPE received. Cleaning up..."

   if [ ! "$sleep_pid" = "" ]; then
      kill -9 "$sleep_pid" || true
   fi

   if [ ! "${SDWDATE_DOWNLOAD_TOOL_PID[$SDWDATE_CURRENT_POOL]}" = "" ]; then
      kill -9 "${SDWDATE_DOWNLOAD_TOOL_PID[$SDWDATE_CURRENT_POOL]}" || true
   fi

   if [ -d "$TEMP_DIR" ]; then
      rm -r "$TEMP_DIR"
   fi

   if [ ! "$DONE_FILE" = "" ]; then
      touch "$DONE_FILE"
   fi
   sdwdate_log "$SCRIPTNAME (not timesync!): signal $SIGNAL_TYPE received. Exiting."
}

sdwdate_signal_sigint() {
   sdwdate_terminate_sclockadj
   SIGNAL_TYPE="SIGINT"
   sdwdate_ex_funct
   exit 130
}

sdwdate_signal_sigterm() {
   sdwdate_terminate_sclockadj
   SIGNAL_TYPE="SIGTERM"
   sdwdate_ex_funct
   exit 143
}

sdwdate_enable_debugging() {
   ## usage: kill -sigusr1 pid

   if [ "$SDWDATE_DEBUG_TRACE_SET" ]; then
      return 0
   fi

   set -x

   exec >  >(tee -a "$LOG_FILE")
   exec 2> >(tee -a "$LOG_FILE" >&2)

   set -o functrace
   shopt -s extdebug

   #trap 'true "BASH_COMMAND: $BASH_COMMAND | FUNCNAME: ${FUNCNAME[1]} | BASH_LINENO: ${BASH_LINENO[0]} | BASH_SOURCE: ${BASH_SOURCE[1]}"' DEBUG
   trap 'true "${FUNCNAME[1]}: $BASH_COMMAND"' DEBUG

   SDWDATE_DEBUG_TRACE_SET="1"
}

sdwdate_signal_sigusr1() {
   sdwdate_enable_debugging
}

sdwdate_get_time_from_remote() {
   local link_unprocessed link_url_part link_comment_part link_url link_port link_processed
   link_unprocessed="$@"
   ## Example link_unprocessed:
   ## atlas777hhh7mcs7.onion:80#Hosted by Thomas White.

   link_url_part="${link_unprocessed%"#"*}"
   ## Examples link_url_part:
   ## atlas777hhh7mcs7.onion:80
   ## atlas777hhh7mcs7.onion
   link_comment_part="${link_unprocessed#*"#"}"
   ## Example link_comment_part:
   ## Hosted by Thomas White.

   if echo "$link_url_part" | grep -q ":" ; then
      ## When link_url_part is for example:
      ## atlas777hhh7mcs7.onion:80
      link_url="${link_url_part%":"*}"
      link_port="${link_url_part#*":"}"
   else
      ## When link_url_part is for example:
      ## atlas777hhh7mcs7.onion
      link_url="$link_url_part"
      link_port="80"
   fi

   link_processed="${link_url}:${link_port}"
   ## Example link_processed:
   ## atlas777hhh7mcs7.onion:80

   sdwdate_download_tool_exit_code[$SDWDATE_CURRENT_POOL]="0"

   local TIME_START
   TIME_START="$(date +%s)"

   sdwdate_log "dispatching SDWDATE_TIME_TOOL_DISPATCH_PRE[$SDWDATE_CURRENT_POOL] (SDW_MODE: $SDW_MODE): ${SDWDATE_TIME_TOOL_DISPATCH_PRE[$SDWDATE_CURRENT_POOL]}"

   if [ "${SDWDATE_TIME_TOOL_DISPATCH_PRE[$SDWDATE_CURRENT_POOL]}" = "" ]; then
      true
   else
      sdwdate_eval ${SDWDATE_TIME_TOOL_DISPATCH_PRE[$SDWDATE_CURRENT_POOL]}
   fi

   sdwdate_log "dispatching SDWDATE_TIME_TOOL_DISPATCH_PRE[$SDWDATE_CURRENT_POOL] done."

   ## Sanity test.
   touch "$TEMP_DIR/$SDWDATE_CURRENT_POOL"
   rm "$TEMP_DIR/$SDWDATE_CURRENT_POOL"
   touch "$TEMP_DIR/$SDWDATE_CURRENT_POOL.stderr"
   rm "$TEMP_DIR/$SDWDATE_CURRENT_POOL.stderr"

   sdwdate_log "get   : $link_processed | local time: $(date) | link_comment_part: $link_comment_part"

   timeout_after="180"
   kill_after="10"

   ## Debugging.
   #timeout_after="0.001"
   #kill_after="0.001"

   timeout --kill-after="$kill_after" "$timeout_after" \
      "/usr/lib/sdwdate/url_to_unixtime" \
         "$PROXY_IP" \
         "$PROXY_PORT" \
         "$link_url" \
         "$link_port" \
         "false" \
         1>"$TEMP_DIR/$SDWDATE_CURRENT_POOL" \
         2>"$TEMP_DIR/$SDWDATE_CURRENT_POOL.stderr" \
         &

   SDWDATE_DOWNLOAD_TOOL_PID[$SDWDATE_CURRENT_POOL]="$!"

   sdwdate_download_tool_exit_code[$SDWDATE_CURRENT_POOL]="0"
   wait "${SDWDATE_DOWNLOAD_TOOL_PID[$SDWDATE_CURRENT_POOL]}" || { sdwdate_download_tool_exit_code[$SDWDATE_CURRENT_POOL]="$?" ; true; };
   unset SDWDATE_DOWNLOAD_TOOL_PID[$SDWDATE_CURRENT_POOL]

   true "INFO: sdwdate_download_tool_exit_code[$SDWDATE_CURRENT_POOL]: ${sdwdate_download_tool_exit_code[$SDWDATE_CURRENT_POOL]}"

   local TIME_END
   TIME_END="$(date +%s)"

   true "SDWDATE_DOWNLOAD_TOOK_TIME[$SDWDATE_CURRENT_POOL]="\$\(\( $TIME_END - $TIME_START \)\)""
   SDWDATE_DOWNLOAD_TOOK_TIME[$SDWDATE_CURRENT_POOL]="$(( $TIME_END - $TIME_START ))"

   local stdout stderr
   stdout="$(cat $TEMP_DIR/$SDWDATE_CURRENT_POOL)" || true
   stderr="$(cat $TEMP_DIR/$SDWDATE_CURRENT_POOL.stderr)" || true

   if [ "${sdwdate_download_tool_exit_code[$SDWDATE_CURRENT_POOL]}" = "124" ]; then
      sdwdate_log "result: $link_processed | local time: $(date) | status: failed  | took: ${SDWDATE_DOWNLOAD_TOOK_TIME[$SDWDATE_CURRENT_POOL]}s | download_tool_exit_code: ${sdwdate_download_tool_exit_code[$SDWDATE_CURRENT_POOL]} | stdout: $stdout | stderr: $stderr | timeout_type: sigterm"
   elif [ "${sdwdate_download_tool_exit_code[$SDWDATE_CURRENT_POOL]}" = "137" ]; then
      sdwdate_log "result: $link_processed | local time: $(date) | status: failed  | took: ${SDWDATE_DOWNLOAD_TOOK_TIME[$SDWDATE_CURRENT_POOL]}s | download_tool_exit_code: ${sdwdate_download_tool_exit_code[$SDWDATE_CURRENT_POOL]} | stdout: $stdout | stderr: $stderr | timeout_type: sigkill"
   fi

   if [ ! "${sdwdate_download_tool_exit_code[$SDWDATE_CURRENT_POOL]}" = "0" ]; then
      sdwdate_log "result: $link_processed | local time: $(date) | status: failed  | took: ${SDWDATE_DOWNLOAD_TOOK_TIME[$SDWDATE_CURRENT_POOL]}s | download_tool_exit_code: ${sdwdate_download_tool_exit_code[$SDWDATE_CURRENT_POOL]} | stdout: $stdout | stderr: $stderr"
      return 0
   fi

   test -f "$TEMP_DIR/$SDWDATE_CURRENT_POOL"
   WEB_DATE_UNIXTIME="$stdout"

   local OLD_UNIXTIME
   OLD_UNIXTIME="$(date +%s)"

   true "SDWDATE_TIME_DIFF[$SDWDATE_CURRENT_POOL]="\$\(\( $WEB_DATE_UNIXTIME - $OLD_UNIXTIME \)\)""
   SDWDATE_TIME_DIFF[$SDWDATE_CURRENT_POOL]="$(( $WEB_DATE_UNIXTIME - $OLD_UNIXTIME ))"

   sdwdate_log "result: $link_processed | local time: $(date) | status: success | took: ${SDWDATE_DOWNLOAD_TOOK_TIME[$SDWDATE_CURRENT_POOL]}s | diff: ${SDWDATE_TIME_DIFF[$SDWDATE_CURRENT_POOL]} second(s)"

   sdwdate_log "dispatching SDWDATE_TIME_TOOL_DISPATCH_POST[$SDWDATE_CURRENT_POOL]: ${SDWDATE_TIME_TOOL_DISPATCH_POST[$SDWDATE_CURRENT_POOL]}"

   if [ "${SDWDATE_TIME_TOOL_DISPATCH_POST[$SDWDATE_CURRENT_POOL]}" = "" ]; then
      true
   else
      sdwdate_eval ${SDWDATE_TIME_TOOL_DISPATCH_POST[$SDWDATE_CURRENT_POOL]}
   fi

   sdwdate_log "dispatching SDWDATE_TIME_TOOL_DISPATCH_POST[$SDWDATE_CURRENT_POOL] done."

   return 0
}

sdwdate_loop() {
   trap "sdwdate_error_handler" ERR

   eval "array=(
      \"\${$SDWDATE_CURRENT_POOL[@]}\"
   )"

   unset remember
   declare -A -g remember

   while true; do
      local array_length
      array_length="${#array[@]}"
      local array_length_remember
      array_length_remember="${#remember[@]}"

      if [ "$array_length" = "0" ]; then
         sdwdate_log "ERROR: $SDWDATE_CURRENT_POOL not configured!"

         ## Check, if we are running in daemon mode.
         if [ "$INTERVAL" = "" ] || [ "$INTERVAL" = "0" ]; then
            ## No daemon mode.
            exit 1
         else
            ## Daemon mode.
            return 1
         fi
      fi

      if [ "$array_length_remember" -ge "$array_length" ]; then
         sdwdate_log "ERROR: No member of the $SDWDATE_CURRENT_POOL could be reached. (debugging information: array_length_remember: $array_length_remember | array_length: $array_length)"

         ## Check, if we are running in daemon mode.
         if [ "$INTERVAL" = "" ] || [ "$INTERVAL" = "0" ]; then
            ## No daemon mode.
            exit 1
         else
            ## Daemon mode.
            return 1
         fi
      fi

      local temp
      temp="$(bc -l <<< "$array_length*$ALLOWED_PER_POOL_FAILURE_RATIO")"
      ## adjust upward / downward
      local allowed_member_failures
      allowed_member_failures="$(/usr/bin/printf "%.f" "$temp")"
      if [ "$allowed_member_failures" = "0" ]; then
         allowed_member_failures="1"
      fi
      sdwdate_log "allowed_member_failures: $allowed_member_failures (debugging information: temp: $temp | SDWDATE_CURRENT_POOL: $SDWDATE_CURRENT_POOL | array_length: $array_length | array_length_remember: $array_length_remember)"

      if [ "$array_length_remember" -ge "$allowed_member_failures" ]; then
         sdwdate_log "ERROR: $allowed_member_failures members of the $SDWDATE_CURRENT_POOL could not be reached. (debugging information: array_length_remember: $array_length_remember | allowed_member_failures: $allowed_member_failures)"

         ## Check, if we are running in daemon mode.
         if [ "$INTERVAL" = "" ] || [ "$INTERVAL" = "0" ]; then
            ## No daemon mode.
            exit 1
         else
            ## Daemon mode.
            return 1
         fi
      fi

      test -e "/dev/random"
      local random_integer
      random_integer="$(( ($(od -An -N2 -i "/dev/random") )%($array_length) ))"

      if [ "${remember[$random_integer]}" = "1" ]; then
         continue
      fi

      ## sets: sdwdate_download_tool_exit_code
      ## sets maybe: WEB_DATE_UNIXTIME
      sdwdate_get_time_from_remote "${array[$random_integer]}"

      if [ ! "${sdwdate_download_tool_exit_code[$SDWDATE_CURRENT_POOL]}" = "0" ]; then
         remember[$random_integer]=1
         continue
      fi

      break
   done

   unset remember

   return 0
}

sdwdate_pick() {
   declare -A -g SDWDATE_RESULT
   declare -A -g SDWDATE_TIME_DIFF

   for SDWDATE_CURRENT_POOL in SDWDATE_POOL_ONE SDWDATE_POOL_TWO SDWDATE_POOL_THREE; do
      ## Temporarily disabling error handler.
      ## Not using
      ## || { sdwdate_loop_return="?"; true; };
      ## here, because then errors any errors caught in sdwdate_loop would be
      ## ignored here.
      trap "" ERR
      sdwdate_loop "$SDWDATE_CURRENT_POOL"
      sdwdate_loop_return="$?"
      trap "sdwdate_error_handler" ERR

      ## Do not continue, if an error was caught.
      if [ ! "$sdwdate_loop_return" = "0" ]; then
         return 0
      fi

      SDWDATE_RESULT[$SDWDATE_CURRENT_POOL]="$WEB_DATE_UNIXTIME"

      true "INFO: SDWDATE_RESULT[$SDWDATE_CURRENT_POOL] = ${SDWDATE_RESULT[$SDWDATE_CURRENT_POOL]} | $(date --date "@${SDWDATE_RESULT[$SDWDATE_CURRENT_POOL]}")"
   done
}

sdwdate_build_median() {
   local results results_list min max
   results="${SDWDATE_TIME_DIFF[SDWDATE_POOL_ONE]} ${SDWDATE_TIME_DIFF[SDWDATE_POOL_TWO]} ${SDWDATE_TIME_DIFF[SDWDATE_POOL_THREE]}"
   sdwdate_log "Results summary: \
one: ${SDWDATE_TIME_DIFF[SDWDATE_POOL_ONE]} | \
two: ${SDWDATE_TIME_DIFF[SDWDATE_POOL_TWO]} | \
three: ${SDWDATE_TIME_DIFF[SDWDATE_POOL_THREE]} | \
second(s)"

   ## Thanks to NotANumber
   ## http://unix.stackexchange.com/a/93949
   results_list=(
      $(
         for item in $results; do
            /usr/bin/printf "%d\n" "$item"
         done | sort -n
      )
   )
   min="${results_list[0]}"
   max="${results_list[${#results_list[*]}-1]}"
   SDWDATE_MEDIAN_TIME_SECONDS="${results_list[${#results_list[*]}/2]}"

   true "SDWDATE_MEDIAN_TIME_NANOSECONDS="\$\(\( $SDWDATE_MEDIAN_TIME_SECONDS \* 1000000000 \)\)""
   SDWDATE_MEDIAN_TIME_NANOSECONDS="$(( $SDWDATE_MEDIAN_TIME_SECONDS * 1000000000 ))"

   sdwdate_log "Min: $min | Max: $max | Median diff: $SDWDATE_MEDIAN_TIME_SECONDS second(s) [$SDWDATE_MEDIAN_TIME_NANOSECONDS nanosecond(s)]"

   local OLD_UNIXTIME
   OLD_UNIXTIME="$(date +%s)"
   true "NEW_UNIXTIME="\$\(\( $OLD_UNIXTIME + $SDWDATE_MEDIAN_TIME_SECONDS \)\)""
   NEW_UNIXTIME="$(( $OLD_UNIXTIME + $SDWDATE_MEDIAN_TIME_SECONDS ))"

   sdwdate_log "local unixtime : $(date +%s) | local time : $(date)"
   sdwdate_log "remote unixtime: $NEW_UNIXTIME | remote time: $(date --date @${NEW_UNIXTIME})"

   if [ "$ECHO_UNIX_TIME" = "true" ]; then
      echo "$NEW_UNIXTIME"
   fi
}

sdwdate_generate_nanoseconds() {
   local ZERO_OR_ONE
   ## Get a random 0 or 1.
   ## Will use this to decide to use plus or minus.
   ##
   ## Thanks to
   ## http://linux.byexamples.com/archives/128/generating-random-numbers/
   test -e "/dev/random"
   ZERO_OR_ONE="$(( 0+($(od -An -N2 -i "/dev/random") )%(0+2) ))"

   if [ "$ZERO_OR_ONE" = "0" ]; then
      NANOSECONDS_PLUS_OR_MINUS="-"
   elif [ "$ZERO_OR_ONE" = "1" ]; then
      NANOSECONDS_PLUS_OR_MINUS="+"
   else
      sdwdate_error_handler "ZERO_OR_ONE is neither 0 nor 1, it's: $ZERO_OR_ONE" || true
   fi

   ## Create a random number between 0 and 999999999.
   ##
   ## Thanks to
   ## https://stackoverflow.com/questions/22887891/how-can-i-get-a-random-dev-random-number-between-0-and-999999999-in-bash
   test -e "/dev/random"
   NANOSECONDS="$(shuf -i0-999999999 -n1 --random-source="/dev/random")"

   local extra_seconds_without_leading_zero extra_seconds
   extra_seconds_without_leading_zero="$(bc -l <<< "scale=9 ; $NANOSECONDS / 1000000000")"
   extra_seconds="$(printf '%3.9f\n' "$extra_seconds_without_leading_zero")"

   sdwdate_log "Made up random extra: ${NANOSECONDS_PLUS_OR_MINUS}${extra_seconds} second[s] [${NANOSECONDS_PLUS_OR_MINUS}${NANOSECONDS} nanosecond(s)]."
}

sdwdate_log_time_before_setting_time() {
   local SDWDATE_NEW_UNIXTIME_AND_NANOSECONDS_BEFORE_SETTING
   SDWDATE_NEW_UNIXTIME_AND_NANOSECONDS_BEFORE_SETTING="$(date +%s.%N)"
   local SDWDATE_NEW_DATE_BEFORE_SETTING
   SDWDATE_NEW_DATE_BEFORE_SETTING="$(date)"
   sdwdate_log "Time before setting: $SDWDATE_NEW_UNIXTIME_AND_NANOSECONDS_BEFORE_SETTING [$SDWDATE_NEW_DATE_BEFORE_SETTING]"
}

sdwdate_log_time_after_setting_time() {
   local SDWDATE_NEW_UNIXTIME_AND_NANOSECONDS_AFTER_SETTING
   SDWDATE_NEW_UNIXTIME_AND_NANOSECONDS_AFTER_SETTING="$(date +%s.%N)"
   local SDWDATE_NEW_DATE_AFTER_SETTING
   SDWDATE_NEW_DATE_AFTER_SETTING="$(date)"
   sdwdate_log "Time after setting using: $SDWDATE_NEW_UNIXTIME_AND_NANOSECONDS_AFTER_SETTING [$SDWDATE_NEW_DATE_AFTER_SETTING]"
}

sdwdate_set_time_using_date() {
   ## sets: NANOSECONDS
   ## sets: NANOSECONDS_PLUS_OR_MINUS
   sdwdate_generate_nanoseconds

   sdwdate_log_time_before_setting_time

   ## sets: SDWDATE_MOVE_TIME_NANOSECONDS_TOTAL
   sdwdate_get_move_time_nanoseonds_total

   local NEW_UNIXTIME_WITH_NANOSECONDS
   NEW_UNIXTIME_WITH_NANOSECONDS="${NEW_UNIXTIME}000000000"

   local SDWDATE_MOVE_TIME_UNIXTIME_WITH_NANOSECONDS
   true "SDWDATE_MOVE_TIME_UNIXTIME_WITH_NANOSECONDS="\$\(\( $NEW_UNIXTIME_WITH_NANOSECONDS $NANOSECONDS_PLUS_OR_MINUS $NANOSECONDS \)\)""
   SDWDATE_MOVE_TIME_UNIXTIME_WITH_NANOSECONDS="$(( $NEW_UNIXTIME_WITH_NANOSECONDS $NANOSECONDS_PLUS_OR_MINUS $NANOSECONDS ))"

   ## {{ SDWDATE_NEW_TIME_FORMATTED_FOR_DATE

   local first_ten last_nine first_ten_string_length last_nine_string_length

   ## unixtime
   first_ten="${SDWDATE_MOVE_TIME_UNIXTIME_WITH_NANOSECONDS:0:10}"

   ## nanoseconds
   last_nine="${SDWDATE_MOVE_TIME_UNIXTIME_WITH_NANOSECONDS:10:19}"

   first_ten_string_length="${#first_ten}"
   last_nine_string_length="${#last_nine}"

   if [ ! "$first_ten_string_length" = "10" ]; then
      sdwdate_error_handler "$FUNCNAME: first_ten: $first_ten | first_ten_string_length: $first_ten_string_length" || true
   fi

   if [ ! "$last_nine_string_length" = "9" ]; then
      sdwdate_error_handler "$FUNCNAME: last_nine: $last_nine | last_nine_string_length: $last_nine_string_length" || true
   fi

   local SDWDATE_NEW_TIME_FORMATTED_FOR_DATE
   ## unixtime.nanoseconds
   SDWDATE_NEW_TIME_FORMATTED_FOR_DATE="$first_ten.$last_nine"

   ## Example SDWDATE_NEW_TIME_FORMATTED_FOR_DATE:
   ## 1405043428.773182656

   ## }} SDWDATE_NEW_TIME_FORMATTED_FOR_DATE

   sdwdate_log "Setting time using \`date\` to $SDWDATE_NEW_TIME_FORMATTED_FOR_DATE..."

   ## Set new time. Syntax: date --set @1396733199.112834496
   ## There is an exception in /etc/sudoers.d/sdwdate.
   sudo /bin/date --set "@${SDWDATE_NEW_TIME_FORMATTED_FOR_DATE}" > /dev/null

   sdwdate_log_time_after_setting_time

   if [ "$SYSTOHC" = "1" ]; then
      sudo /sbin/hwclock --systohc
   fi
}

sdwdate_terminate_sclockadj() {
   if [ "$SDWDATE_SUBSHELL_SCLOCKADJ_PID" = "" ]; then
      return 0
   fi

   local pid_still_running SDWDATE_SUBSHELL_SCLOCKADJ_EXIT_CODE
   SDWDATE_SUBSHELL_SCLOCKADJ_EXIT_CODE="0"
   pid_still_running="0"
   kill -0 "$SDWDATE_SUBSHELL_SCLOCKADJ_PID" || { pid_still_running="$?" ; true; };

   if [ "$pid_still_running" = "0" ]; then
      sdwdate_log "$FUNCNAME: subshell for sclockadj with pid $SDWDATE_SUBSHELL_SCLOCKADJ_PID still running. Terminating..."
      kill -sigterm "$SDWDATE_SUBSHELL_SCLOCKADJ_PID" || true
      wait "$SDWDATE_SUBSHELL_SCLOCKADJ_PID" || { SDWDATE_SUBSHELL_SCLOCKADJ_EXIT_CODE="$?" ; true; };
      sdwdate_log "$FUNCNAME: subshell for sclockadj with pid $SDWDATE_SUBSHELL_SCLOCKADJ_PID Terminated. Exit code: $SDWDATE_SUBSHELL_SCLOCKADJ_EXIT_CODE"
   else
      wait "$SDWDATE_SUBSHELL_SCLOCKADJ_PID" || { SDWDATE_SUBSHELL_SCLOCKADJ_EXIT_CODE="$?" ; true; };
      sdwdate_log "$FUNCNAME: subshell for sclockadj with pid $SDWDATE_SUBSHELL_SCLOCKADJ_PID no longer running. Exit code: $SDWDATE_SUBSHELL_SCLOCKADJ_EXIT_CODE"
   fi

   ## Not required.
   ## Done by function sdwdate_subshell_time_end.
   #sdwdate_log_time_after_setting_time

   if [ "$SDWDATE_SUBSHELL_SCLOCKADJ_EXIT_CODE" = "0" ]; then
       sdwdate_log "$FUNCNAME: subshell for sclockadj with pid $SDWDATE_SUBSHELL_SCLOCKADJ_PID exited with expected zero exit code: $SDWDATE_SUBSHELL_SCLOCKADJ_EXIT_CODE"
   elif [ "$SDWDATE_SUBSHELL_SCLOCKADJ_EXIT_CODE" = "130" ]; then
       sdwdate_log "$FUNCNAME: subshell for sclockadj with pid $SDWDATE_SUBSHELL_SCLOCKADJ_PID exited with expected non-zero exit code (sigint): $SDWDATE_SUBSHELL_SCLOCKADJ_EXIT_CODE"
   elif [ "$SDWDATE_SUBSHELL_SCLOCKADJ_EXIT_CODE" = "143" ]; then
       sdwdate_log "$FUNCNAME: subshell for sclockadj with pid $SDWDATE_SUBSHELL_SCLOCKADJ_PID exited with expected non-zero exit code (sigterm): $SDWDATE_SUBSHELL_SCLOCKADJ_EXIT_CODE"
   else
       sdwdate_log "$FUNCNAME: subshell for sclockadj with pid $SDWDATE_SUBSHELL_SCLOCKADJ_PID exited with unexpected non-zero exit code: $SDWDATE_SUBSHELL_SCLOCKADJ_EXIT_CODE"
       SDWDATE_SUBSHELL_SCLOCKADJ_PID=""
       ## Not using sdwdate_error_handler to prevent and endless loop.
       sdwdate_error "$FUNCNAME: subshell for sclockadj exited with unexpected non-zero exit code: $SDWDATE_SUBSHELL_SCLOCKADJ_EXIT_CODE"
   fi
   SDWDATE_SUBSHELL_SCLOCKADJ_PID=""
}

sdwdate_get_move_time_nanoseonds_total() {
   local SDWDATE_MOVE_TIME_SECONDS_TOTAL first_char

   true "SDWDATE_MOVE_TIME_NANOSECONDS_TOTAL="\$\(\( $SDWDATE_MEDIAN_TIME_NANOSECONDS $NANOSECONDS_PLUS_OR_MINUS $NANOSECONDS \)\)""
   SDWDATE_MOVE_TIME_NANOSECONDS_TOTAL="$(( $SDWDATE_MEDIAN_TIME_NANOSECONDS $NANOSECONDS_PLUS_OR_MINUS $NANOSECONDS ))"

   SDWDATE_MOVE_TIME_SECONDS_TOTAL="$(bc -l <<< "scale=2 ; $SDWDATE_MOVE_TIME_NANOSECONDS_TOTAL / 1000000000")"
   SDWDATE_MOVE_TIME_SECONDS_TOTAL="$(printf '%.2f\n' "$SDWDATE_MOVE_TIME_SECONDS_TOTAL")"

   first_char=${SDWDATE_MOVE_TIME_SECONDS_TOTAL::1}
   if [ ! "$first_char" = "-" ]; then
      SDWDATE_MOVE_TIME_SECONDS_TOTAL="+$SDWDATE_MOVE_TIME_SECONDS_TOTAL"
   fi

   sdwdate_log "require time change: $SDWDATE_MOVE_TIME_SECONDS_TOTAL second(s) [$SDWDATE_MOVE_TIME_NANOSECONDS_TOTAL nanosecond(s)]"
}

sdwdate_set_time_using_sclockadj() {
   ## sets: NANOSECONDS
   ## sets: NANOSECONDS_PLUS_OR_MINUS
   sdwdate_generate_nanoseconds

   ## Not required.
   ## Done by function sdwdate_subshell_time_start.
   #sdwdate_log_time_before_setting_time

   ## sets: SDWDATE_MOVE_TIME_NANOSECONDS_TOTAL
   sdwdate_get_move_time_nanoseonds_total

   local first_char
   first_char=${SDWDATE_MOVE_TIME_NANOSECONDS_TOTAL::1}

   local sclockadj_add_or_subtract
   if [ "$first_char" = "-" ]; then
      local SDWDATE_MOVE_TIME_NANOSECONDS_TOTAL_WITHOUT_SIGN
      SDWDATE_MOVE_TIME_NANOSECONDS_TOTAL_WITHOUT_SIGN="${SDWDATE_MOVE_TIME_NANOSECONDS_TOTAL#?}"
      sclockadj_add_or_subtract="--subtract $SDWDATE_MOVE_TIME_NANOSECONDS_TOTAL_WITHOUT_SIGN"
   else
      sclockadj_add_or_subtract="--add $SDWDATE_MOVE_TIME_NANOSECONDS_TOTAL"
   fi

   ## Setting the INLINEDIR environment variable for ruby-inline, that requires
   ## a non-group writeable cache dir.

   local SDWDATE_SCLOCKADJ_COMMAND
   ## There is an exception in /etc/sudoers.d/.
   SDWDATE_SCLOCKADJ_COMMAND="\
      sudo \
         INLINEDIR=$SDW_CACHE_DIR \
            /usr/lib/sdwdate/sclockadj \
               $SDWDATE_SCLOCKADJ_VERBOSE \
               $SDWDATE_SCLOCKADJ_CHANGE_DATE \
               $SDWDATE_SCLOCKADJ_FIRST_WAIT \
               $SDWDATE_SCLOCKADJ_SYSTOHC \
               --move-min $SDWDATE_SCLOCKADJ_MOVE_MIN \
               --move-max $SDWDATE_SCLOCKADJ_MOVE_MAX \
               --wait-min $SDWDATE_SCLOCKADJ_WAIT_MIN \
               --wait-max $SDWDATE_SCLOCKADJ_WAIT_MAX \
               $sclockadj_add_or_subtract \
   "

   sdwdate_log "Launching into background: $SDWDATE_SCLOCKADJ_COMMAND"

   sclockadj_subshell_fifo="$TEMP_DIR/sclockadj.sclockadj_subshell_fifo"
   rm --force "$sclockadj_subshell_fifo"
   mkfifo "$sclockadj_subshell_fifo"
   test -r "$sclockadj_subshell_fifo"

   {
      sdwdate_subshell_time_start() {
         SDWDATE_SUBSHELL_SCLOCKADJ_TIME_START="$(date +%s)"
         local SDWDATE_NEW_UNIXTIME_AND_NANOSECONDS_BEFORE_SETTING
         SDWDATE_NEW_UNIXTIME_AND_NANOSECONDS_BEFORE_SETTING="$(date +%s.%N)"
         local SDWDATE_NEW_DATE_BEFORE_SETTING
         SDWDATE_NEW_DATE_BEFORE_SETTING="$(date)"
         echo "Time before running sclockadj: $SDWDATE_NEW_UNIXTIME_AND_NANOSECONDS_BEFORE_SETTING [$SDWDATE_NEW_DATE_BEFORE_SETTING]"
      }

      sdwdate_subshell_time_end() {
         SDWDATE_SUBSHELL_SCLOCKADJ_TIME_END="$(date +%s)"
         true "SDWDATE_SUBSHELL_SCLOCKADJ_TOOK_TIME_SECONDS="\$\(\( $SDWDATE_SUBSHELL_SCLOCKADJ_TIME_END - $SDWDATE_SUBSHELL_SCLOCKADJ_TIME_START \)\)""
         SDWDATE_SUBSHELL_SCLOCKADJ_TOOK_TIME_SECONDS="$(( $SDWDATE_SUBSHELL_SCLOCKADJ_TIME_END - $SDWDATE_SUBSHELL_SCLOCKADJ_TIME_START ))"
         SDWDATE_SUBSHELL_SCLOCKADJ_TOOK_TIME_MINUTES="$(bc -l <<< "scale=2 ; $SDWDATE_SUBSHELL_SCLOCKADJ_TOOK_TIME_SECONDS / 60")"
         SDWDATE_SUBSHELL_SCLOCKADJ_TOOK_TIME_HOURS="$(bc -l <<< "scale=2 ; $SDWDATE_SUBSHELL_SCLOCKADJ_TOOK_TIME_MINUTES / 60")"
         ## Add leading zero.
         SDWDATE_SUBSHELL_SCLOCKADJ_TOOK_TIME_MINUTES="$(printf '%.2f\n' "$SDWDATE_SUBSHELL_SCLOCKADJ_TOOK_TIME_MINUTES")"
         SDWDATE_SUBSHELL_SCLOCKADJ_TOOK_TIME_HOURS="$(printf '%.2f\n' "$SDWDATE_SUBSHELL_SCLOCKADJ_TOOK_TIME_HOURS")"
         echo "was running for $SDWDATE_SUBSHELL_SCLOCKADJ_TOOK_TIME_SECONDS s [~ $SDWDATE_SUBSHELL_SCLOCKADJ_TOOK_TIME_MINUTES min] \
[~ $SDWDATE_SUBSHELL_SCLOCKADJ_TOOK_TIME_HOURS h]."
         unset SDWDATE_SUBSHELL_SCLOCKADJ_TIME_START
         unset SDWDATE_SUBSHELL_SCLOCKADJ_TIME_END
         unset SDWDATE_SUBSHELL_SCLOCKADJ_TOOK_TIME_SECONDS
         unset SDWDATE_SUBSHELL_SCLOCKADJ_TOOK_TIME_MINUTES
         unset SDWDATE_SUBSHELL_SCLOCKADJ_TOOK_TIME_HOURS
         local SDWDATE_NEW_UNIXTIME_AND_NANOSECONDS_AFTER_SETTING
         SDWDATE_NEW_UNIXTIME_AND_NANOSECONDS_AFTER_SETTING="$(date +%s.%N)"
         local SDWDATE_NEW_DATE_AFTER_SETTING
         SDWDATE_NEW_DATE_AFTER_SETTING="$(date)"
         echo "Time after running sclockadj: $SDWDATE_NEW_UNIXTIME_AND_NANOSECONDS_AFTER_SETTING [$SDWDATE_NEW_DATE_AFTER_SETTING]"
      }

      sdwdate_subshell_wait() {
         echo "$FUNCNAME: Waiting for pid to finish SDWDATE_SCLOCKADJ_COMMAND_PID: $SDWDATE_SCLOCKADJ_COMMAND_PID"
         SDWDATE_SCLOCKADJ_COMMAND_EXIT_CODE="0"
         wait "$SDWDATE_SCLOCKADJ_COMMAND_PID" || { SDWDATE_SCLOCKADJ_COMMAND_EXIT_CODE="$?" ; true; };
         echo "$FUNCNAME: SDWDATE_SCLOCKADJ_COMMAND_PID: $SDWDATE_SCLOCKADJ_COMMAND_PID | SDWDATE_SCLOCKADJ_COMMAND_EXIT_CODE: $SDWDATE_SCLOCKADJ_COMMAND_EXIT_CODE"
      }

      sdwdate_subshell_trap_sigterm() {
         ## Interrupted sdwdate_subshell_wait.
         if [ "$SDWDATE_SCLOCKADJ_COMMAND_PID" = "" ]; then
            return 0
         fi
         ## There is a /etc/sudoers.d exception.
         echo "executing: sudo /usr/lib/sdwdate/sclockadj_kill_helper $SDWDATE_SCLOCKADJ_COMMAND_PID"
         sclockadj_kill_helper_output="$(sudo /usr/lib/sdwdate/sclockadj_kill_helper "$SDWDATE_SCLOCKADJ_COMMAND_PID" 2>&1)"
         echo "sclockadj_kill_helper_output: $sclockadj_kill_helper_output"
         unset sclockadj_kill_helper_output
         echo "$FUNCNAME: Execute sdwdate_subshell_wait again to set SDWDATE_SCLOCKADJ_COMMAND_EXIT_CODE."
         sdwdate_subshell_wait
      }

      trap "sdwdate_subshell_trap_sigterm" SIGTERM

      ## There is a /etc/sudoers.d exception.
      sudo /usr/lib/sdwdate/sclockadj_debug_helper || true

      sdwdate_subshell_time_start

      $SDWDATE_SCLOCKADJ_COMMAND 2>&1 &
      SDWDATE_SCLOCKADJ_COMMAND_PID="$!"

      sdwdate_subshell_wait ## Might get interrupted by signal sigterm.

      sdwdate_subshell_time_end

      echo "exit code: $SDWDATE_SCLOCKADJ_COMMAND_EXIT_CODE"

      exit "$SDWDATE_SCLOCKADJ_COMMAND_EXIT_CODE"
   } > "$sclockadj_subshell_fifo" 2>&1 &

   SDWDATE_SUBSHELL_SCLOCKADJ_PID="$!"
   sdwdate_log "Started subshell for sclockadj with pid: $SDWDATE_SUBSHELL_SCLOCKADJ_PID"

   {
      sdwdate_log "sdwdate_subshell_read: start"
      while read -r sclockadj_line; do
         sdwdate_log "sdwdate_subshell_read: sclockadj reports: $sclockadj_line"
      done < "$sclockadj_subshell_fifo"
      sdwdate_log "sdwdate_subshell_read: end"
   } &
}

sdwdate_maybe_set_new_time() {
   sdwdate_terminate_sclockadj

   if [ "$DONT_SET_DATE" = "1" ]; then
      return 0
   fi

   ## Do not needlessly try to change time, when there is no difference.
   if [ "$SDWDATE_MEDIAN_TIME_SECONDS" = "0" ]; then
      sdwdate_log "No need to set clock."
      return 0
   fi

   if [ "$NO_MOVE_FORWARD" = "1" ]; then
      if [ "$SDWDATE_MEDIAN_TIME_SECONDS" -gt "0" ]; then
         sdwdate_log "Not setting clock forward."
         return 0
      fi
   fi

   if [ "$NO_MOVE_BACKWARDS" = "1" ]; then
      if [ "$SDWDATE_MEDIAN_TIME_SECONDS" -lt "0" ]; then
         sdwdate_log "Not setting clock backwards."
         return 0
      fi
   fi

   if [ "$SDW_MODE" = "startup" ]; then
      if [ "$SDWDATE_USE_SCLOCKADJ_WHEN_STARTUP" = "1" ]; then
         sdwdate_set_time_using_sclockadj
      else
         sdwdate_set_time_using_date
      fi
   elif [ "$SDW_MODE" = "restartup" ]; then
      if [ "$SDWDATE_USE_SCLOCKADJ_WHEN_RESTARTUP" = "1" ]; then
         sdwdate_set_time_using_sclockadj
      else
         sdwdate_set_time_using_date
      fi
   elif [ "$SDW_MODE" = "daemon" ]; then
      if [ "$SDWDATE_USE_SCLOCKADJ_WHEN_DAEMON" = "1" ]; then
         sdwdate_set_time_using_sclockadj
      else
         sdwdate_set_time_using_date
      fi
   else
      sdwdate_error_handler 'SDW_MODE is neither "startup" nor "daemon".'
   fi
}

sdwdate_dispatcher_prerequisite() {
   if [ "$DISPATCH_PREREQUISITE" = "" ]; then
      true "DISPATCH_PREREQUISITE is empty, skipping."
   else
      while true; do
         sdwdate_no_duplicate_log "dispatching prerequisite (SDW_MODE: $SDW_MODE) (LD_PRELOAD: $LD_PRELOAD): $DISPATCH_PREREQUISITE"

         local prerequisite_exit_code
         prerequisite_exit_code="0"
         prerequisite_output="$(eval $DISPATCH_PREREQUISITE 2>&1)" || { prerequisite_exit_code="${PIPESTATUS[0]}" ; true; };

         true "prerequisite_exit_code: $prerequisite_exit_code"
         true "prerequisite_output: $prerequisite_output"

         if [ "$prerequisite_exit_code" = "0" ]; then
            ## Ok.
            sdwdate_log "DISPATCH_PREREQUISITE exited $prerequisite_exit_code, continuing..."
            break
         elif [ "$prerequisite_exit_code" = "1" ]; then
            ## Error.
            sdwdate_error_handler "DISPATCH_PREREQUISITE exited $prerequisite_exit_code | $prerequisite_output | requested explicit exiting..." || true
         elif [ "$prerequisite_exit_code" = "2" ]; then
            ## Wait.
            sdwdate_no_duplicate_log "DISPATCH_PREREQUISITE exited $prerequisite_exit_code | $prerequisite_output | waiting..."
            sleep 10 &
            sleep_pid="$!"
            wait "$sleep_pid" || true
            unset sleep_pid
         else
            ## Unexpected error.
            sdwdate_error_handler "DISPATCH_PREREQUISITE exited $DISPATCH_PREREQUISITE, neither 0, 1, or 2. | $prerequisite_output | unexpected error, exiting..." || true
         fi

      done
   fi
}

sdwdate_eval() {
   eval_output="$(eval ${1+"$@"} 2>&1)"
   #eval_output="$(eval bash -x ${1+"$@"} 2>&1)"
   #sdwdate_log "eval_output: $eval_output"
}

sdwdate_dispatcher_pre() {
   if [ "$DISPATCH_PRE" = "" ]; then
      true "DISPATCH_PRE is empty, skipping."
   else
      sdwdate_no_duplicate_log "dispatching pre (SDW_MODE: $SDW_MODE): $DISPATCH_PRE"
      sdwdate_eval $DISPATCH_PRE
   fi
}

sdwdate_failed() {
   rm --force "$SUCCESS_FILE"
   touch "$DONE_FILE"
}

sdwdate_success() {
   touch "$FIRST_SUCCESS_FILE"
   touch "$SUCCESS_FILE"
   touch "$DONE_FILE"
}

sdwdate_dispatcher_post_success() {
   if [ "$DISPATCH_POST_SUCCESS" = "" ]; then
      true "DISPATCH_POST_SUCCESS is empty, skipping."
   else
      sdwdate_log "dispatching post_success (SDW_MODE: $SDW_MODE): $DISPATCH_POST_SUCCESS"
      sdwdate_eval $DISPATCH_POST_SUCCESS
      sdwdate_log "dispatching post_success done."
   fi
}

sdwdate_dispatcher_post_failure() {
   if [ "$DISPATCH_POST_FAILURE" = "" ]; then
      true "DISPATCH_POST_FAILURE is empty, skipping."
   else
      sdwdate_log "dispatching post_failure (SDW_MODE: $SDW_MODE): $DISPATCH_POST_FAILURE"
      sdwdate_eval $DISPATCH_POST_FAILURE
      sdwdate_log "dispatching post_failure done."
   fi
}

sdwdate_error_test() {
   if [ -f "/var/lib/sdw_error" ]; then
      sdwdate_error_handler "Test file /var/lib/sdw_error to force test an error exists." || true
      sleep 10 &
      sleep_pid="$!"
      wait "$sleep_pid" || true
      unset sleep_pid
   fi
}

sdwdate_sleep() {
   ## INTERVAL: in minutes
   ## sleep: in seconds

   local minutes
   if [ "$RANDOMIZE" = "1" ]; then
      test -e "/dev/random"
      minutes="$(( ($(od -An -N2 -i "/dev/random") )%($INTERVAL) ))"
      if [ "$MIN_INTERVAL" -ge "$minutes" ]; then
         true "minutes="\$\(\( $minutes + $MIN_INTERVAL \)\)""
         minutes="$(( $minutes + $MIN_INTERVAL ))"
      fi
   else
      minutes="$INTERVAL"
   fi

   local seconds
   true "seconds="\$\(\( $minutes \* 60 \)\)""
   seconds="$(( $minutes * 60 ))"

   sdwdate_log "Sleeping for $minutes minutes. (RANDOMIZE: $RANDOMIZE)"

   sleep "$seconds" &
   sleep_pid="$!"
   wait "$sleep_pid" || true
   unset sleep_pid
}

sdwdate_maybe_read_config_folder() {
   local grep_exit_code
   grep_exit_code="$?"
   echo "${1+"$@"}" | grep --quiet "\-\-noconfig" || { grep_exit_code="$?" ; true; };
   if [ "$grep_exit_code" = "0" ]; then
      true "Found --noconfig, skip reading config folder."
   else
      ## Not found, let's read config folder.
      sdwdate_read_config_folder
   fi
}

sdwdate_maybe_parse_cmd_options() {
   if [ "$PARSE_CMD_ONLY_ON_STARTUP" = "1" ]; then
      if [ "$ALREADY_PARSED_CDM_ON_STARTUP" = "1" ]; then
         true "ALREADY_PARSED_CDM_ON_STARTUP is 1, not parsing cmd options again."
      else
         ALREADY_PARSED_CDM_ON_STARTUP="1"
         sdwdate_parse_cmd_options
      fi
   else
      sdwdate_parse_cmd_options ${1+"$@"}
   fi
}

sdwdate_maybe_sleep_or_exit() {
   ## Check, if we are running in daemon mode.
   if [ "$INTERVAL" = "" ] || [ "$INTERVAL" = "0" ]; then
      ## No daemon mode.
      exit 0
   else
      ## Daemon mode.
      SDW_MODE="daemon"
      sdwdate_sleep
   fi
}

sdwdate_main() {
   sdwdate_sanity_tests

   while true; do
      sdwdate_maybe_read_config_folder ${1+"$@"}
      sdwdate_maybe_parse_cmd_options ${1+"$@"}
      sdwdate_defaults
      sdwdate_log "Running sdwdate... pid: $$ | LD_PRELOAD: $LD_PRELOAD"
      sdwdate_preparation
      if [ "$DEBUG" = "1" ]; then
         sdwdate_enable_debugging
      fi

      sdwdate_error_test

      sdwdate_dispatcher_pre
      sdwdate_dispatcher_prerequisite

      sdwdate_pick

      ## Do not continue, if an error was caught.
      if [ ! "$sdwdate_loop_return" = "0" ]; then
         sdwdate_failed
         sdwdate_dispatcher_post_failure
      else
         sdwdate_build_median
         sdwdate_maybe_set_new_time
         sdwdate_success
         sdwdate_dispatcher_post_success
      fi

      sdwdate_maybe_sleep_or_exit
   done
}
