#!/bin/bash

## Copyright (C) 2012 - 2021 ENCRYPTED SUPPORT LP <adrelanos@whonix.org>
## See the file COPYING for copying conditions.

if [ -f /usr/libexec/helper-scripts/pre.bsh ]; then
   source /usr/libexec/helper-scripts/pre.bsh
fi

set -e

rm --force /usr/libexec/sdwdate/sclockadj

if [ "$1" = "purge" ]; then
   rm --force "/var/log/sdwdate.log"
   rm -r --force "/var/cache/sdwdate"
fi

#DEBHELPER#
