#!/bin/bash

## Copyright (C) 2021 - 2022 ENCRYPTED SUPPORT LP <adrelanos@whonix.org>
## See the file COPYING for copying conditions.

## usage:
## usr/libexec/config-test > ./config-test.txt

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "$MYDIR"

cmd="python3 ../../usr/lib/python3/dist-packages/sdwdate/config.py"

echo ""

$cmd "0" "test"
$cmd "1" "test"
$cmd "2" "test"

# $cmd "0" "production"
# $cmd "1" "production"
# $cmd "2" "production"
