#!/bin/bash

set -e

if [ ! "$(id -u)" = "0" ]; then
   echo "ERROR: Must run as root!" >&2
   exit 2
fi

if [ -d "/usr/lib/qubes" ]; then
   randomized_unix_time="$(timeout --kill-after="5" "5" /usr/lib/qubes/qrexec-client-vm dom0 qubes.GetRandomizedTime)"
else
   echo "ERROR: Not implemented in Non-Qubes-Whonix. See: https://www.whonix.org/wiki/Troubleshooting#Clock_Fix" >&2
   exit 3
fi

date --set "@$randomized_unix_time" >/dev/null

service sdwdate restart
