#! /usr/bin/env python

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

## Usage:
## /usr/lib/sdwdate/date_to_unixtime "Mon, 20 Oct 2014 14:10:30 GMT" ; echo $?
## 1413814230
## 0

## Test:
## date --date "@$(/usr/lib/sdwdate/date_to_unixtime "Mon, 20 Oct 2014 14:10:30 GMT")"
## Mon Oct 20 14:10:30 UTC 2014

import sys
from dateutil.parser import parse

date=str(sys.argv[1])

try:
   ## Thanks to:
   ## eumiro
   ## http://stackoverflow.com/a/3894047/2605155
   unixtime = parse(date).strftime('%s')
except ValueError as e:
   print >> sys.stderr, "Parsing date from server failed. | date: %s | dateutil ValueError: %s" % (date, e)
   sys.exit(2)

print "%s" % (unixtime)

sys.exit(0)
