#!/bin/bash

## Copyright (C) 2017 - 2018 ENCRYPTED SUPPORT LP <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

set -e

sudo --non-interactive rm --force /var/run/sdwdate/first_success
sudo --non-interactive -u sdwdate touch /var/run/sdwdate/clock_jump_do_once
sudo --non-interactive systemctl --no-pager --no-block restart sdwdate
