#!/bin/bash

## Copyright (C) 2012 - 2018 ENCRYPTED SUPPORT LP <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

kill -s sigkill $(pgrep -f "/usr/lib/sdwdate/sclockadj")

exit 0
