#!/bin/bash

## Copyright (C) 2012 - 2018 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

kill -sigkill $(pgrep -f "ruby /usr/lib/sdwdate/sclockadj")

exit 0
