#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

set -x

find /var/cache/sdwdate -printf "%p %u %g %m\n"
true "\$?: $?"
