#!/bin/bash

## Copyright (C) 2017 - 2018 ENCRYPTED SUPPORT LP <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

set -x
set -e

date_cmd(){
   date -u +"%Y-%m-%d %T"
}

if [ -f /run/qubes/this-is-templatevm ]; then
   echo "$(date_cmd) - $0 - INFO - Skipping, because run in TemplateVM."
   exit 0
fi

if [ ! "$(id -u)" = "0" ]; then
   echo "$(date_cmd) - $0 - ERROR - Must run as root!" | sudo -u sdwdate tee -a /var/log/sdwdate.log || true
   exit 2
fi

if command -v "qubesdb-read" >/dev/null 2>&1 ; then
   true
else
   echo "$(date_cmd) - $0 - INFO - Clock fix after resume not implemented in Non-Qubes-Whonix. See: https://www.whonix.org/wiki/Troubleshooting#Clock_Fix" | sudo -u sdwdate tee -a /var/log/sdwdate.log || true
   exit 3
fi

## Defensive measure to not mess up file permissions.
mkdir --parents /run/sdwdate
chown --recursive sdwdate:sdwdate /run/sdwdate

tor_restart_maybe() {
   if test -f /run/sdwdate/tor_was_running.status ; then
      echo "$(date_cmd) - $0 - INFO - Deleting /run/sdwdate/tor_was_running.status..." | sudo -u sdwdate tee -a /var/log/sdwdate.log || true
      rm --force /run/sdwdate/sdwdate_was_running.status
      echo "$(date_cmd) - $0 - INFO - Done, deleted /run/sdwdate/tor_was_running.status." | sudo -u sdwdate tee -a /var/log/sdwdate.log || true

      echo "$(date_cmd) - $0 - INFO - Restarting Tor..." | sudo -u sdwdate tee -a /var/log/sdwdate.log || true
      systemctl --no-pager restart tor@default
      echo "$(date_cmd) - $0 - INFO - Done, restarted Tor." | sudo -u sdwdate tee -a /var/log/sdwdate.log || true
   else
      echo "$(date_cmd) - $0 - INFO - File /run/sdwdate/tor_was_running.status did not exist, meaning we previously did not stop Tor so not starting it now." | sudo -u sdwdate tee -a /var/log/sdwdate.log || true
   fi
}

## Previously in suspend-pre sdwdate
## - Tor was stopped.
## - sdwdate was stopped.
## - Whonix firewall entered timesync-fail-closed mode.
##
## Now in this script:
## - 1. roughly fix the time using `date`
## - 2. restart Tor
## - 3. restart sdwdate fresh so it also sets the time using `date`
## - 4. (outside of this script) Once sdwdate succeeded,
##      whonix-firewall-sdwdate-watcher.service should enter Whonxi firewall in
##      full mode.
##
## For an ISP level observer this should look like a reboot.

## Do not interfere with the clock if the service was stopped.
if test -f /run/sdwdate/sdwdate_was_running.status ; then
   echo "$(date_cmd) - $0 - INFO - Deleting /run/sdwdate/sdwdate_was_running.status..." | sudo -u sdwdate tee -a /var/log/sdwdate.log || true
   rm --force /run/sdwdate/sdwdate_was_running.status
   echo "$(date_cmd) - $0 - INFO - Done, deleted /run/sdwdate/sdwdate_was_running.status." | sudo -u sdwdate tee -a /var/log/sdwdate.log || true

   ## Workaround for a Qubes bug.
   ## https://github.com/Whonix/updates-status/issues/1
   randomized_unix_time="$(timeout --kill-after="5" "5" /usr/lib/qubes/qrexec-client-vm dom0 qubes.GetRandomizedTime)" || \
      echo "$(date_cmd) - $0 - ERROR - /usr/lib/qubes/qrexec-client-vm had non-zero exit code." | sudo -u sdwdate tee -a /var/log/sdwdate.log || true

   if [[ "$randomized_unix_time" =~ ^[+-]?[0-9]+\.?[0-9]*$ ]]; then
      echo "$(date_cmd) - $0 - INFO - date before roughly fixing it: $(date -u)" | sudo -u sdwdate tee -a /var/log/sdwdate.log || true
      date --set "@$randomized_unix_time" >/dev/null
      echo "$(date_cmd) - $0 - INFO - date after roughly fixing it : $(date -u)" | sudo -u sdwdate tee -a /var/log/sdwdate.log || true
   else
      echo "$(date_cmd) - $0 - ERROR - randomized_unix_time: '$randomized_unix_time'" | sudo -u sdwdate tee -a /var/log/sdwdate.log || true
   fi

   tor_restart_maybe

   echo "$(date_cmd) - $0 - INFO - Running /usr/lib/sdwdate/restart_fresh..." | sudo -u sdwdate tee -a /var/log/sdwdate.log || true
   /usr/lib/sdwdate/restart_fresh
   echo "$(date_cmd) - $0 - INFO - Done, with /usr/lib/sdwdate/restart_fresh." | sudo -u sdwdate tee -a /var/log/sdwdate.log || true

   ## Whonix firewall full mode
   ##
   ## After sdwdate restart, sdwdate will on success recreate the status file
   ## '/run/sdwdate/first_success'.
   ##
   ## ( whonix-[gw|ws]-firewall ) /lib/systemd/system/whonix-firewall-sdwdate-watcher.service /
   ## ( helper-scripts ) /usr/lib/helper-scripts/firewall-restarter
   ## will notice this, and restart Whonix firewall in full mode.

   exit 0
else
   echo "$(date_cmd) - $0 - INFO - File /run/sdwdate/sdwdate_was_running.status did not exist, meaning we previously did not stop sdwdate so not starting it now." | sudo -u sdwdate tee -a /var/log/sdwdate.log || true
fi

## Make sure Tor is restarted even if sdwdate was not running during suspend-pre.
tor_restart_maybe
