#!/bin/bash

set -x
set -e

if [ ! "$(id -u)" = "0" ]; then
   echo "$0 ERROR: Must run as root!" >> /var/log/sdwdate.log
   exit 2
fi

if service sdwdate status >/dev/null ; then
   echo "$0 INFO: Creating /var/run/sdwdate/was_running.status..." >> /var/log/sdwdate.log
   touch /var/run/sdwdate/was_running.status
   echo "$0 INFO: Done, created /var/run/sdwdate/was_running.status." >> /var/log/sdwdate.log

   if command -v whonix_firewall >/dev/null 2>&1 ; then
      if [ -d "/usr/lib/qubes" ]; then
         ## Whonix firewall timesync-fail-closed mode
         echo "$0 INFO: Entering Whonix firewall timesync-fail-closed mode." >> /var/log/sdwdate.log
         firewall_mode="timesync-fail-closed" whonix_firewall
         echo "$0 INFO: Done, entered Whonix firewall timesync-fail-closed mode." >> /var/log/sdwdate.log
      else
         echo "$0 INFO: Not entering Whonix firewall timesync-fail-closed mode,
because non-interactive /usr/lib/sdwdate/clock-fix is not implemented for Non-Qubes-Whonix. See:
https://phabricator.whonix.org/T551" >> /var/log/sdwdate.log
      fi
   else
      true "$0 INFO: Whonix firewall not installed, probably running outside of Whonix." >> /var/log/sdwdate.log
   fi

   echo "$0 INFO: Stopping sdwdate..." >> /var/log/sdwdate.log
   service sdwdate stop
   echo "$0 INFO: Done, stopped sdwdate." >> /var/log/sdwdate.log
else
   echo "$0 INFO: sdwdate was not running, no need to stop it." >> /var/log/sdwdate.log
fi
