#! /usr/bin/env python

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

## TODO:
## - add dependency python-requests to debian/control
## - any reason good reason to use libcurl instead or does python-requests support all we need?
## - check if it really uses "--head" by inspecting traffic
## - command line parameter to maybe use https (as option true or false [not for .onion])
## - command line parameter to set url
## - command line parameter for proxy settings yes/no
## - command line parameter verbose option?
## - command line parameter for curl user agent
## - command line parameter for timeout
## - force use TLSv1, not SSL
## - error handling
## - max file size?
## - anything else?

import requests
import sys
from dateutil.parser import parse

url = "https://check.torproject.org"

## Does not support socks proxies yet.
## https://github.com/kennethreitz/requests/issues/2156
proxies = {
    'http' : "socks5://127.0.0.1:9050",
    'https' : "socks5://127.0.0.1:9050"
}

proxies = {
  "http": "http://127.0.0.1:9050",
  "https": "http://127.0.0.1:9050",
}

try:
   #response = requests.head(url, proxies=proxies)

   ## Fails as expected.
   #cafile = '/usr/share/ca-certificates/mozilla/StartCom_Certification_Authority.crt'
   ## Works as expected.
   cafile = '/usr/share/ca-certificates/mozilla/DigiCert_High_Assurance_EV_Root_CA.crt'
   response = requests.get(url, verify=cafile)

except requests.exceptions.ConnectionError as e:
   print >> sys.stderr, "Request failed. | url: %s | ConnectionError: %s" % (url, e)
   sys.exit(1)

content = response.headers
date = response.headers.get('date')

date = date.strip()

if date == "":
   print >> sys.stderr, "Parsing date from server failed. | Empty date."
   sys.exit(2)

try:
   ## Thanks to:
   ## eumiro
   ## http://stackoverflow.com/a/3894047/2605155
   unixtime = parse(date).strftime('%s')
except ValueError as e:
   print >> sys.stderr, "Parsing date from server failed. | date: %s | dateutil ValueError: %s" % (date, e)
   sys.exit(3)

print "%s" % (unixtime)

sys.exit(0)
