#!/usr/bin/python

## Copyright (C) 2015 troubadour <trobador@riseup.net>
## Copyright (C) 2015 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

import sys, socks
from dateutil.parser import parse

def data_to_date_string_start_position(data):
    date_string_start_position = data.find('Date:')

    if date_string_start_position == -1:
        ## not found, check if lowercase.
        date_string_start_position = data.find('date:')

    if date_string_start_position == -1:
        ## "Date:" not found.
        print >> sys.stderr, 'Parsing HTTP header date failed.'
        print >> sys.stderr, 'HTTP header data:\n%s' % (data)
        sys.exit(3)

    date_string_start_position = date_string_start_position + 6
    return date_string_start_position

def data_to_http_time(data, date_string_start_position):
    http_time = ''
    ## max accepted string length.
    http_time = data[date_string_start_position:date_string_start_position + 29].strip()

    http_time_string_length = len(http_time)

    ## min string length = max string length.
    if http_time_string_length < 29:
        print >> sys.stderr, 'HTTP header date string too short.'
        print >> sys.stderr, 'HTTP header date length: %s' % http_time_string_length
        print >> sys.stderr, 'HTTP header data:\n%s' % (data)
        print >> sys.stderr, 'HTTP header date value: "%s"' % (http_time)
        sys.exit(4)

    return http_time

def unixtime_sanity_check(data, http_time, parsed_unixtime):
    try:
        unixtime_digit = int(parsed_unixtime)

    except ValueError as e:
        print >> sys.stderr, 'parsed_unixtime conversion failed!'
        print >> sys.stderr, 'data: %s' % (data)
        print >> sys.stderr, 'http_time: %s' % (http_time)
        print >> sys.stderr, 'parsed_unixtime: %s' % (parsed_unixtime)
        print >> sys.stderr, 'parsed_unixtime not numeric!'
        sys.exit(6)

    unixtime_string_length_is = len(parsed_unixtime)
    unixtime_string_length_max = 10

    if unixtime_string_length_is > unixtime_string_length_max:
        print >> sys.stderr, 'parsed_unixtime conversion failed!'
        print >> sys.stderr, 'data: %s' % (data)
        print >> sys.stderr, 'http_time: %s' % (http_time)
        print >> sys.stderr, 'parsed_unixtime: %s' % (parsed_unixtime)
        print >> sys.stderr, 'unixtime_string_length_is: %s' % (unixtime_string_length_is)
        print >> sys.stderr, 'unixtime_string_length_max: %s' % (unixtime_string_length_max)
        print >> sys.stderr, 'parsed_unixtime has excessive string length!'
        sys.exit(7)

    return parsed_unixtime

def request_data_from_remote_server(socket_ip, socket_port, url):
    s = socks.socksocket()
    s.setproxy(socks.PROXY_TYPE_SOCKS5, socket_ip, socket_port)

    try:
        s.connect((url, 80))

    except Exception as e:
        if str(e).startswith('__init__'):
            print >> sys.stderr, 'connect error: URL "%s" not found.' % url
        else:
            print >> sys.stderr, 'connect error: %s' % (e)
        sys.exit(2)

    s.send('HEAD / HTTP/1.0\r\n\r\n')

    data = ''
    buf = s.recv(1024)
    while len(buf):
        data += buf
        buf = s.recv(1024)
    s.close()

    return data

def http_time_to_parsed_unixtime(data, http_time):
    try:
        ## Thanks to:
        ## eumiro
        ## http://stackoverflow.com/a/3894047/2605155
        parsed_unixtime = parse(http_time).strftime('%s')

    except ValueError as e:
        print >> sys.stderr, 'Parsing http_time from server failed!'
        print >> sys.stderr, 'HTTP header data:\n%s' % (data)
        print >> sys.stderr, 'http_time: %s' % (http_time)
        print >> sys.stderr, 'dateutil ValueError: %s' % (e)
        sys.exit(5)

    return(parsed_unixtime)

def parse_command_line_parameters():
    try:
        socket_ip = sys.argv[1]
        socket_port = int(sys.argv[2])
        url = sys.argv[3]

    except (IndexError) as e:
        print >> sys.stderr, "Parsing command line parameter failed. | e: %s" % (e)
        sys.exit(1)

    return(socket_ip, socket_port, url)

def main():
   socket_ip, socket_port, url = parse_command_line_parameters()
   data = request_data_from_remote_server(socket_ip, socket_port, url)
   date_string_start_position = data_to_date_string_start_position(data)
   http_time = data_to_http_time(data, date_string_start_position)
   parsed_unixtime = http_time_to_parsed_unixtime(data, http_time)
   unixtime = unixtime_sanity_check(data, http_time, parsed_unixtime)

   print "%s" % unixtime

main()
