#!/bin/bash

## Copyright (C) 2017 - 2021 ENCRYPTED SUPPORT LP <adrelanos@whonix.org>
## See the file COPYING for copying conditions.

set -e

if [ ! "$(id -u)" = "0" ]; then
    true "$0: ERROR: Must be run as root!"
    exit 1
fi

## run as root
rm --force /run/anondate/tor_certificate_lifetime_set
## run as user sdwdate
rm --force /run/sdwdate/tor_certificate_lifetime_set

rm --force /run/sdwdate/first_success
rm --force /run/sdwdate/clock_jump_do_once

sudo --non-interactive -u sdwdate touch /run/sdwdate/clock_jump_do_once

systemctl --no-pager --no-block restart sdwdate

true "$0: OK"
